spring.application.name=car-auction-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/auction_platform
spring.datasource.username=admin
spring.datasource.password=admin

jwt.secret=change-me-this-is-a-dev-only-secret-key-min-32-bytes-long-1234567890
jwt.expiration-ms=86400000